import type { Metadata } from "next";
import { Khula } from "next/font/google";
import "./globals.css";

const khula = Khula({
  weight: ["300", "400", "600", "700", "800"],
  variable: "--font-khula",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${khula.variable} antialiased`}>{children}</body>
    </html>
  );
}
